package Modelo;
// Generated Nov 18, 2020 9:01:11 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Comparator;

/**
 * FacturasLin generated by hbm2java
 */
public class FacturasLin implements java.io.Serializable {

    private FacturasLinId id;
    private Articulos articulos;
    private FacturasCab facturasCab;
    private BigDecimal cantidad;
    private BigDecimal precio;
    private BigDecimal dtolinea;
    private BigDecimal ivalinea;

    public FacturasLin() {
    }

    public FacturasLin(FacturasLinId id, Articulos articulos, FacturasCab facturasCab, BigDecimal cantidad, BigDecimal precio, BigDecimal dtolinea, BigDecimal ivalinea) {
        this.id = id;
        this.articulos = articulos;
        this.facturasCab = facturasCab;
        this.cantidad = cantidad;
        this.precio = precio;
        this.dtolinea = dtolinea;
        this.ivalinea = ivalinea;
    }

    @Override
    public String toString() {
        return "FacturasLin{" + "id=" + id + ", articulos=" + articulos + ", facturasCab=" + facturasCab + ", cantidad=" + cantidad + ", precio=" + precio + ", dtolinea=" + dtolinea + ", ivalinea=" + ivalinea + '}';
    }

    public FacturasLinId getId() {
        return this.id;
    }

    public void setId(FacturasLinId id) {
        this.id = id;
    }

    public Articulos getArticulos() {
        return this.articulos;
    }

    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }

    public FacturasCab getFacturasCab() {
        return this.facturasCab;
    }

    public void setFacturasCab(FacturasCab facturasCab) {
        this.facturasCab = facturasCab;
    }

    public BigDecimal getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    public BigDecimal getDtolinea() {
        return this.dtolinea;
    }

    public void setDtolinea(BigDecimal dtolinea) {
        this.dtolinea = dtolinea;
    }

    public BigDecimal getIvalinea() {
        return this.ivalinea;
    }

    public void setIvalinea(BigDecimal ivalinea) {
        this.ivalinea = ivalinea;
    }

    public static Comparator<FacturasLin> ordenarLineas = new Comparator<FacturasLin>() {

        @Override
        public int compare(FacturasLin o1, FacturasLin o2) {
            long nRecibo1 = o1.getId().getLineafac();
            long nRecibo2 = o2.getId().getLineafac();

            return (int) nRecibo1 - (int) nRecibo2;
        }

    };

}
